// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlNUKKU8BOzkeSebvIzmITclJ2bduSTy0',
    appId: '1:11665655714:web:13ae419443c15049ec14fb',
    messagingSenderId: '11665655714',
    projectId: 'athlicoder-da282',
    authDomain: 'athlicoder-da282.firebaseapp.com',
    storageBucket: 'athlicoder-da282.firebasestorage.app',
    measurementId: 'G-RCP735HF6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOYseZK9KbF3yKthI20mQMpwd-LQrHm5A',
    appId: '1:11665655714:android:0fed8fdb39072a74ec14fb',
    messagingSenderId: '11665655714',
    projectId: 'athlicoder-da282',
    storageBucket: 'athlicoder-da282.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3az2QfVr_lLewQbgV1KXAKQcBSx0Ap_I',
    appId: '1:11665655714:ios:51cdf1d4a8a7112bec14fb',
    messagingSenderId: '11665655714',
    projectId: 'athlicoder-da282',
    storageBucket: 'athlicoder-da282.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3az2QfVr_lLewQbgV1KXAKQcBSx0Ap_I',
    appId: '1:11665655714:ios:51cdf1d4a8a7112bec14fb',
    messagingSenderId: '11665655714',
    projectId: 'athlicoder-da282',
    storageBucket: 'athlicoder-da282.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlNUKKU8BOzkeSebvIzmITclJ2bduSTy0',
    appId: '1:11665655714:web:cfbbb1a813d38875ec14fb',
    messagingSenderId: '11665655714',
    projectId: 'athlicoder-da282',
    authDomain: 'athlicoder-da282.firebaseapp.com',
    storageBucket: 'athlicoder-da282.firebasestorage.app',
    measurementId: 'G-N16PJ7EM5W',
  );
}
